<?php
$players = [];
$mode = isset($_POST['mode']) ? $_POST['mode'] : 'local';
$difficulty = isset($_POST['difficulty']) ? $_POST['difficulty'] : 'medium';

// Process players
foreach ($_POST as $key => $value) {
    if (strpos($key, 'player') === 0 && !str_contains($key, 'color') && !str_contains($key, 'mode') && !str_contains($key, 'difficulty')) {
        $index = str_replace('player', '', $key);
        // Check if color exists for this index
        if(isset($_POST["color$index"])) {
            $name = htmlspecialchars($value);
            $color = htmlspecialchars($_POST["color$index"]);
            $players[] = ['name' => $name, 'color' => $color];
        }
    }
}

// If no players (direct access), redirect
if(empty($players)) {
    header("Location: index.html");
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Snake & Ladder - Game</title>
  <link href="style.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet">
</head>
<body>

<div class="bg-wrapper">
  
  <div class="game-container">
    
    <!-- Sidebar: Players & Info -->
    <div class="left-info-panel">
      <h3 class="text-center mb-4" style="font-family: 'Luckiest Guy'; color: var(--accent-color); font-size: 2rem; letter-spacing: 2px;">PLAYERS</h3>
      <div id="player-list">
        <?php foreach ($players as $index => $p): ?>
          <div class="player-card" id="player-card-<?= $index ?>">
            <div class="color-dot" style="background-color: <?= $p['color'] ?>;">
                <?= substr($p['name'], 0, 1) ?>
            </div>
            <div class="player-info">
                <h4><?= $p['name'] ?></h4>
                <p>Score: <span id="score-<?= $index ?>">0</span></p>
                <div class="timer-badge" id="timer-<?= $index ?>" style="display:none;">10s</div>
            </div>
          </div>
        <?php endforeach; ?>
      </div>

      <div class="mt-4 text-center">
          <button class="btn-custom" style="font-size: 0.9rem; padding: 12px 25px; background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.2);" onclick="location.href='index.html'">EXIT GAME</button>
      </div>
    </div>

    <!-- Game Board -->
    <div class="board-wrapper">
      <div class="board" id="game-board">
        <!-- Generated by JS -->
      </div>
    </div>

    <!-- Dice Panel -->
    <div class="sidebar" style="display: flex; flex-direction: column; align-items: center; justify-content: center;">
      <h3 style="font-family: 'Luckiest Guy'; color: var(--secondary-color);" class="pulse">ROLL IT!</h3>
      
      <div class="dice-container" onclick="rollDice()">
        <div id="dice" data-side="1">
          <div class="side side-1"><div class="dot"></div></div>
          <div class="side side-2"><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-3"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-4"><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-5"><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-6"><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
        </div>
      </div>

      <p style="margin-top: 20px; font-size: 0.9rem; opacity: 0.8;">Click dice to roll</p>
    </div>

  </div>

</div>

<script src="game-logic.js"></script>
<script>
  // Initialize game with PHP data
  const playerData = <?= json_encode($players) ?>;
  const mode = "<?= $mode ?>";
  const difficulty = "<?= $difficulty ?>";
  
  window.onload = function() {
      initGame(mode, difficulty, playerData);
  };
</script>

</body>
</html>
