<?php
$game_id = isset($_GET['game_id']) ? $_GET['game_id'] : null;
$player_id = isset($_GET['player_id']) ? $_GET['player_id'] : null;

if (!$game_id || !$player_id) {
    header("Location: lobby.php");
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Snake & Ladder - Online</title>
  <link href="style.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet">
</head>
<body>

<div class="bg-wrapper">
  
  <div class="game-container">
    
    <!-- Sidebar: Players & Info -->
    <div class="left-info-panel">
      <h3 class="text-center mb-4" style="font-family: 'Luckiest Guy'; color: var(--accent-color); font-size: 2rem; letter-spacing: 2px;">ONLINE</h3>
      
      <div id="player-list">
        <!-- Populated by JS -->
      </div>
      
      <div id="chat-container">
        <h5 style="font-size: 0.85rem; margin-bottom: 10px; opacity: 0.7; font-weight: 700; text-transform: uppercase; letter-spacing: 1px;">Chat Messages</h5>
        <div id="chat-messages" style="height: 180px; overflow-y: auto; font-size: 0.85rem; margin-bottom: 10px; padding-right: 5px;">
          <!-- Messages here -->
        </div>
        <div class="chat-input-wrapper">
          <input type="text" id="chat-input" placeholder="Say hello...">
          <button onclick="sendMessage()">Send</button>
        </div>
      </div>

      <div class="mt-4 text-center">
          <button class="btn-custom" style="font-size: 0.9rem; padding: 12px 25px; background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.2);" onclick="exitGame()">EXIT GAME</button>
      </div>
    </div>

    <!-- Game Board -->
    <div class="board-wrapper">
      <div class="board" id="game-board">
        <!-- Generated by JS -->
      </div>
    </div>

    <!-- Dice Panel -->
    <div class="sidebar" style="display: flex; flex-direction: column; align-items: center; justify-content: center;">
      <h3 style="font-family: 'Luckiest Guy'; color: var(--secondary-color);" class="pulse">ROLL IT!</h3>
      
      <div class="dice-container" onclick="rollDice()">
        <div id="dice" data-side="1">
          <div class="side side-1"><div class="dot"></div></div>
          <div class="side side-2"><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-3"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-4"><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-5"><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
          <div class="side side-6"><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
        </div>
      </div>

      <p style="margin-top: 20px; font-size: 0.9rem; opacity: 0.8;">Click dice to roll</p>
    </div>

  </div>

</div>

<script src="online-game.js?v=<?= time() ?>"></script>
<script>
  window.onload = function() {
      initOnlineGame(<?= $game_id ?>, <?= $player_id ?>);
  };
</script>

</body>
</html>
